### ISSUE TITLE
Daily message limit issue

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox-feature-requests#10]
_From @Ylmzef on January 31, 2016 21:37_

Daily message limit not working with new im.
I set the daily message limit to 5 but users can send unlimited messages.

_Copied from original issue: moxi9/phpfox#1047_

**Comment by Data66PF** [comment]
The IM disables the PM settings. You can use one or the other but not both. At this time, there are no settings for the IM to regulate what users can do in it.

**Comment by Data66PF** [comment]
Marked an enhancement as we need the settings back for this.

**Comment by Data66PF** [comment]
We brought back the settings. Would you please check and see if they work for you on v4.3 build 5?

**Comment by Ylmzef** [comment]
Sure

**Comment by Ylmzef** [comment]
It's still doesn't working..

**Comment by Data66PF** [comment]
Since we brought back the settings, please test with 4.3.2 build 3 and if they don't work, please post a bug for it.

**Comment by Ylmzef** [comment]
I tested with 4.3.2b3 too.

**Comment by Data66PF** [comment]
Please go to the bug section and post a bug for it. Thanks.
