### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox-feature-requests#101]
Good Day, Phpfox using Nginx and you develop the site using Nginx. I would like to know how do you setup your /etc/nginx/conf.d/default.conf to be the same what original phpfox setup for this.

Thank You so much!

**Comment by Data66PF** [comment]
This is for feature requests, not for hosting. Please see http://phpfoxsolutions.com as they use nginx for their servers and are our recommended hosts.
