### ISSUE TITLE
View IP sessions user activity in admincp

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox-feature-requests#102]
The current ip sessions view does not provide anything useful. In the old version of phpfox we used to be able to see the user's ip sessions activity so you can get a sense whether someone may be doing something malicious or not. Such as the pages they visit and stuff. 

It would be awesome to bring this feature back.

**Comment by Data66PF** [comment]
The reason this was disabled is because it caused sites to crash due to large log_session table. We cannot bring this back.
