### ISSUE TITLE
Share to your wall and a friends wall

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#105]
Hello :) 

this will be useful for a load of people

Where you've got these options to share

"to a friends wall" and "to your wall" 

It'd be really useful if another option was added 

so it'd be 

Share

"To a friends Wall

"To you're wall

"to your's and ---- wall

think a lot of people will find that useful :)

**Comment by RaymondBenc** [comment]
Our development team has looked over this feature from a pragmatic view and feel its best if this was developed by a 3rd party vender to extend the functionality as we would like to keep this routine separate in our core product.

**Comment by phpfoxdev** [comment]
FYI,
- share to your wall, we do check for Privacy box: only me, friends, etc.
- share to friend wall, we have no control on this
Then no good way to combine these two flows
