### ISSUE TITLE
Notification alert not disappearing when opened

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#108]
Hello :) 

I've found a little bug, 

I found it in the PHpfox demo, and I've tested it on my site 

i've upgraded to 4.3 build 5 and its still there, 

When you get a notification, it gives you an alert, but when you open the notification, the alert doesn't go away until you open up the notifications again

**Comment by Data66PF** [comment]
Please post this in the bug tracker. Feature requests are not for bugs. Note that this was probably already reported so please search first.
