### ISSUE TITLE
Need to build a separate module same as blog module

### ISSUE THREAD

**Issue by supreshc-persistent** [moxi9/phpfox-feature-requests#113]
Need to build a same module as existing blog module as requirement is for having to bloging system in the application ,so only certain user groups allowed to blog in new built blog system.

My requirement is to replicate the Blog module where only certain users will have the ability to post and have different blog categories. My approach was to copy the entire Blog module and make changes to the MySQL table names to use for the replicated Blog module.

Could anyone provide inputs on the above.

**Comment by Data66PF** [comment]
Please post this at the community as this area is for small feature requests. Note that TemplateMechanic.com already has an Articles module that he is porting to v4. You can see it working on my own site, I use it for my tutorials in v3, http://scripttechs.com/article/
