### ISSUE TITLE
Layout improvement for Forums

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox-feature-requests#117]
Forums looking so complex currently.
*Sub-categories and description same text colort and same size. it shows complex and not understandable.
*Thread starter showing above thread title in threads list page. it shows complex and not understandable.
*Share & Thread Tools links showing with big space between above and before.
*And please add pagination for forums.
*Also add reply button under the page too.

**Comment by Data66PF** [comment]
Please provide screenshots of what you would like.

**Comment by Data66PF** [comment]
As this is more than one issue, we have to close it as our instructions say one issue. Please open one issue per request.
