### ISSUE TITLE
Video ads in phpfox timelinr

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#118]
Please ad video ads in our advertises if an advertiseruploads a video he wants to adverise lets afveryise the video in the feed by playing the video with no sound if a users wants to hear video then he will click the video to hear it.

**Comment by GreenMan123** [comment]
Like youtube there are advertisrs while you are watching a video on the top of the video ike that. 
For users who upload video they could earn money by just sharing video like youtubers because there would be a relavant advertulise at the top of the vide... Share the earnings with video uploader.  Before  the video uploads, while the video is playing, after the video has finished  playing.  The advertise could be video, text, links ..... Etc

**Comment by Data66PF** [comment]
This is too big a feature for this section as it is for small feature requests. When we have a way for third party developers to respond, we will show them things like this as the ad system would need to be totally remade for something like this to work.
