### ISSUE TITLE
Make the video engageing in phpfox

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#119]
When users upload Video for there friend it should be engaging for there friends in such a way it is not something they would just scroll down because the video will play with nosound when it loads but if the users prefers to play the video it will click the video and the sound will be released

**Comment by Data66PF** [comment]
So you mean you want it to start playing like FB does when someone scrolls down the feed?

**Comment by Lukey199223** [comment]
If Phpfox builds this feature, can we also have an option to turn the auto play off ? :) thank you :)

**Comment by GreenMan123** [comment]
Yes
