### ISSUE TITLE
New Phpfox version of the "BBC Code editor"

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#122]
Hello :) 

I've found a bug with The BBC Code editor (I think Jinker's made it, but I'm not 100% sure who did) 

when I Enable it, it doesn't work on forum's but works on "pages" , but with it enabled, when you click onto the forum or pages , it freezes the page so you have to refresh the page to carry on

it'd be awesome, if PHPfox made their own version of this as it's a really cool feature to have :) ,

**Comment by Data66PF** [comment]
Jinkers is back with his app for this so we will need to reject this

**Comment by Lukey199223** [comment]
:) I forgot to come back to reply on here when I heard Jinkers is back aha :)
