### ISSUE TITLE
fcgi ???

### ISSUE THREAD

**Issue by mikelcoreclark** [moxi9/phpfox-feature-requests#127]
Ok I enabled short urls to see if that would help and it doesn't. The script, with this at fcgi mode, is looking for ajax in the main site root instead of in PF.Base and so it can't find it. I think your server is not displaying errors (display_errors must be enabled)
There is also an error showing in the developer browser console with debug enabled. I suggest to post all of this at github in two error reports. One for FCGI error finding ajax and let them know it was first not set to short urls and then set to short urls and both had the same result - it could not find ajax to post to the feed.
The second bug is the "syntax error, unexpected end of file" for the feed. 
…/¬file/¬cache/¬template/¬feed_template_default_block_entry.html.php_ajax.php45
Open: /home/lasanza/public_html/PF.Base/file/cache/template/feed_template_default_block_entry.html.php_ajax.php

<?php
Phpfox::getLib('template')->getBuiltFile('feed.block.content'); 
?>

<?php (($sPlugin = Phpfox_Plugin::get('feed.template_block_entry_3')) ? eval($sPlugin) : false); ?>
</div>

Regarding the cover photos. You cannot remove default sizes unless you completely change the script. I added back the 1024. If you removed any other default sizes, you need to put those back.
 - ScriptTechs

thanks
mikel

**Comment by Data66PF** [comment]
This seems more a bug than feature. will close.
