### ISSUE TITLE
Earn money from posting something

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#128]
Other social network make there user earn money by just sharing something .there earning is considered how much there content has become engaging. Like YouTube. There more the content you share gets more views or more engments from other users the more you get to earn money. How much should the user earn money should be set by admin how much persentage%.

**Comment by Data66PF** [comment]
There is a points system. You could already use points to reward users with points and let them spend things on marketplace items, ads, egifts. There is also an app already for using webmoney, https://store.phpfox.com/product/1278/emoney
