### ISSUE TITLE
Allow user name to be anything

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#135]
Hello :)

it'd be awesome if a member could set their user name as anything they'd like 

every username a member enters then clicks save , its saying "Please provide a user name" in a red box

**Comment by Data66PF** [comment]
In AdminCP >> Settings >> User you will see a Settings link. Click that and you will see user settings. In that, you will see:

Profile User ID Connection
Set to True if you would like to have user profiles connected via their user ID#. Set to False if you would like to have user profiles connected via their user name. 

Note if you connect via their user ID# you will allow your members the ability to use non-supported characters which are not allowed if connecting a profile with their user name. 

Warning: This action cannot be reversed. 
This setting may lock users out if you force log in by their user names 

Is that feature not working for you? Note that you cannot change back if you change this setting on a live site so try on your development site.

**Comment by Lukey199223** [comment]
Thank you :) , this feature is working for me, but I was just wondering when members on my site are updating their user name it says "Please provide user name" , but the connection via #ID must sort that out :) thank you :)

**Comment by Data66PF** [comment]
What do you mean? Screenshots are nice for explaining things.

**Comment by Lukey199223** [comment]
Sorry Donna, When I Wrote this, I was using my phone and it doesnt take screenshots anymore because its a bit broke haha, I mean, Whatever I enter as a new username, and I click save, it gives me an error message saying "please Provide username" , will provide screenshots tomorrow, when I get on my laptop :)

**Comment by Lukey199223** [comment]
Sorry for not getting back yesterday, been up to my eye balls with stuff to do haha, but certain times I enter a username, its not accepting it, but its been fine the last few days, I'll test it for the next week or so and let you know if the problem continues :)

**Comment by Data66PF** [comment]
closed for now. reopen if you find what you mean. :)

**Comment by Lukey199223** [comment]
I've been testing this since you replied and it seems to be fine now , it seems to be accepting anything as a username :) , 

I' noticed I wasnt on build 5 (I thought I Was but I missed an upgrade in my mind haha) , then I'll test it to see if it still works , 

thanks Donna :)
