### ISSUE TITLE
2Checkout Integration like in V3

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#137]
Hello most of my advertisers and users don't want to create a paypal account for one time payment from the phone or pc with a credit or debit card so please bring back 2CheckOut to phpfox. To let them them choose between PayPal and 2CheckOut.

**Comment by Data66PF** [comment]
This is best for third party developers.

**Comment by GreenMan123** [comment]
Paypal is not accepted everywhere by some countries.  You should consider that...

**Comment by Data66PF** [comment]
YouNet already has a payment gateway app with lots of options though. We cannot cut out third party developers.
