### ISSUE TITLE
Content Privacy Settings

### ISSUE THREAD

**Issue by erick260** [moxi9/phpfox-feature-requests#138]
On the new v4 that just came out i think i found a bug.
Issue:
When adding new content you will see: Control who can see these photo(s). try to set the privacy settings. Click the Privacy box, go down to custom Create a friends list, or choose a friends list that you have. You will not be able to save that page.

   In addition this, i've found 1 more i think..
In Site Settings Friends only Community. Note: In order for this to work you must enable the option Section Privacy Item Browsing
I do not see anywhere in the admincp where we can find the "Section Privacy Item Browsing settings"

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox please post the bug there but please note that we do have instructions for only one issue at a time per report so if you have two issues, please post two bugs.
