### ISSUE TITLE
Adult Content Settings:

### ISSUE THREAD

**Issue by erick260** [moxi9/phpfox-feature-requests#139]
A: When users upload a video, photo, blog post, other to have a mandatory Question YES OR NO  "mark as adult." . 

B: Site Settings: We can have the option of adding the Mature Content settings to the "User Roles" that we want to be able to view the Mature Content. "What IF we want users that upgraded to be able to view the Mature Content on the website."

C: Account Settings Page :On the Account settings page for the users to be able to Select Yes Or No to View the Mature Content on the website. (If their Membership  level has access to this as stated in #B.) 

TIP: I noticed you have a feature Mature Content, but this comes with no extra features at all. The way you current have it is when users have to Edit their Photo to be able to choose this, not on he upload page of where it gets added.

D: Content  Moderation: When Admins/Staff Reviews content for approval for us to have an option of marking the item as adult when approving it. Content Marked as Mature Content  by staff cannot be undone by users..

E:    Privacy Concern:  The way you currently have it, is for users to be able to select Yes contains Mature Content. But the user is able to Re-edit the image and mark it as no for mature content. This is a Privacy Concern for me. Content marked as Mature Content should remain, only Staff should be able to undo this.. (As stated in #D)

**Comment by Data66PF** [comment]
This does not follow the posted rules. It has more than one item.
