### ISSUE TITLE
add a user from admin section

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox-feature-requests#140]
Hi i would like to add a user(s) but I cannot find how to in admin, so I assume its not possible, that brings me here to add as a feature request. 

I want to be able to add user(s) via admin, the user(s) I add could be admin, or moderator etc.
I don't want to have to add via front end, to much hassle. just from admin section. require username or email address based on settings and a password in order to create.

 this would be so helpful please..

Thanks
Spiro

**Comment by Data66PF** [comment]
Please use the app for that. https://store.phpfox.com/product/855/stock-users
