### ISSUE TITLE
The ability for the admin to edit more of the Core features 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#141]
Hello :) 

It'd be awesome if we could edit more of the Core features without risking void'ing' our sites, 

for example, I Want to move all of the "Upload a photo" etc to the profiles pages instead of the main pages on the navigation menu so I can get rid of the main navigation pages (hide them) to go along with my plan for my site

its not the best feature request, but I think it'd be useful for a lot of us :)

**Comment by Data66PF** [comment]
This is far to vague and general. We already have many ways in which you can edit features. You can do template overrides, change menus, etc. This is not something we will be doing.

**Comment by Lukey199223** [comment]
Sorry for the Vague'ness' Donna, I'm getting a developer to do it for me :) , Basically All I Wanted was the the option to have "Upload an image" on the photo's page on someones profile as well as having it on the main photo page etc :)
