### ISSUE TITLE
Disable the Developers link and tab for some time

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#145]
Disable the Developers link and tab for some time

**Comment by GreenMan123** [comment]
Like thr disable or enable tab

**Comment by GreenMan123** [comment]
For the Developers

**Comment by Data66PF** [comment]
What do you mean? Do you have a screenshot? There is no Developers link in the Neutron v4 footer like v3 Nebula had.

**Comment by GreenMan123** [comment]
![1464075056024](https://cloud.githubusercontent.com/assets/13588067/15495803/de57035a-219a-11e6-833b-167559b2bd48.jpg)
![1464074983530](https://cloud.githubusercontent.com/assets/13588067/15495813/e5abe67a-219a-11e6-86da-9ef35c1df36e.jpg)
please make the link for developer gets to be enable and disable from the admin panel because it is a bit early for ny website to request my website users intgrate with there website or to create apps for my website

**Comment by Data66PF** [comment]
Ok you hadn't said this was for the demo. We are fixing that. thanks.
