### ISSUE TITLE
While watch photos keep comments tab beside the photo to the right

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#146]
While watch photos keep comments tab beside the photo to the right

**Comment by Lukey199223** [comment]
I want this too :) like facebook but with the option to edit the css of it

**Comment by Data66PF** [comment]
Please provide a screenshot of how you want it to show.

**Comment by GreenMan123** [comment]
![11](https://cloud.githubusercontent.com/assets/13588067/15830590/f66f76e8-2c21-11e6-8bae-391a1c970d1b.JPG)

**Comment by Data66PF** [comment]
The problem with this is when there are huge images that take the full screen.
