### ISSUE TITLE
[v4.2.0] Videos URL

### ISSUE THREAD

**Issue by Data66Tech** [moxi9/phpfox-feature-requests#15]
_From @Spaninet on January 19, 2016 0:4_

The URL of videos page is https://stage.phpfox.com/v/ instead of https://stage.phpfox.com/videos in v4.2.0.

![Screenshot](https://stage.phpfox.com/file/pic/photo/2016/01/f31a093c99f5f1cb4e731936c7494010_1024.png)

_Copied from original issue: moxi9/phpfox#959_

**Comment by Data66PF** [comment]
If we change this, we need to let clients that are using the videofeed app know to delete it as that uses /videos

**Comment by Data66PF** [comment]
_From @SpeakLife on February 4, 2016 10:56_

That is a good idea Donna because I had to delete my other video feed that was using /videos. So I'm now using the /v.
