### ISSUE TITLE
Add multiple video's to comments/messages

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#150]
I think it'd be awesome and really useful to be able to add multiple video's to comments and messages ::)

**Comment by GreenMan123** [comment]
I wish it was also possible to post multiple( Admin control the number of uploads at a time) photos, Video, Audio files yo shows Status.....

**Comment by spirogg** [comment]
Me also that would be great feature.

**Comment by Data66PF** [comment]
Please adjust this for either comments or messages.
