### ISSUE TITLE
Consider using Plyr for video playback consistency

### ISSUE THREAD

**Issue by ashdelacroix** [moxi9/phpfox-feature-requests#153]
Instead of relying on the browser's own rendering of the video player, which can give an inconsistent look-and-feel across browsers and operating systems, I recommend the implementation of the open source Plyr script, which supports HTML5 video, as well as YouTube and Vimeo. It is a much more polished player that can be customised and provides a consistent, in-line volume and scrubbing controls. Also supports closed captioning / subtitles.

https://plyr.io/#video

**Comment by ashdelacroix** [comment]
Plyr has just added a new feature at my request which would disable the right-click context menu on their video player. This would take care of my request to phpFox to find some way of preventing casual theft of video content and hot-linking, by taking some basic measures to obfuscate certain functionality. With Plyr, access to "Download Video" and "Copy Video URL" menu items can be disabled, so it would be fantastic to have Plyr within phpFox and allow us to disable the right-click context menu via an option within AdminCP. Many thanks.

**Comment by spirogg** [comment]
This is very nice. I would also be interested
