### ISSUE TITLE
SEO H1, H2, H3, H4 tags missing

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#154]
Dear team, 
since my previous post was rejected as I had put multiple SEO improvements in one request, I am posting them individually here:

SEO Improvement #1:

H1, H2, H3, H4 tags are missing.. This can be added to blogs, events and forums.. all titles cab be in H1 tags and sub headers in H2 tags. Especially if blogs can be given default SEO features like wordpress it will see a great improvement in ranking for the content added..

**Comment by RaymondBenc** [comment]
We currently provide H1 tags on all items that contain a viewable object. Can you provide some working examples of what you mean?

**Comment by srikumar101** [comment]
Yes Raymond.. somehow i missed noticing H1 tags earlier.. Thanks.. you can close this issue
