### ISSUE TITLE
SEO ALT attributes missing 

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#155]
SEO Improvement #2 :

ALT attribute in Image tags should be auto populated with either image name or caption or description of photos being uploaded.

**Comment by RaymondBenc** [comment]
Our developers have looked over this routine and any images passed via our script uses our internal library, which includes the **alt** attribute. Additionally images passed by other means cannot be controlled at times. If you find any specific images, please report this is a bug report and we can look it over.

Thanks
