### ISSUE TITLE
SEO for blogs 

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#157]
SEO Improvement 4: 

Can we have a placeholder for adding keywords/tags and description while drafting a blog itself? Because each blog will be unique and these generic keywords may not be of much help for SEO.

**Comment by srikumar101** [comment]
Any reason for closure?

**Comment by RaymondBenc** [comment]
I looked this over with our development team and since we include the title in the meta description and keywords this should suffice as the proper keywords to use for each entry. This sort of feature would be best suited to be developed by a 3rd party vendor to extend the Blog module.

**Comment by srikumar101** [comment]
ok Thanks Raymond
