### ISSUE TITLE
SEO - Publisher tag

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#159]
SEO Improvement 6

Add rel="Publisher" tag whic is for linking site to Google+ Page which will improve ranking.

**Comment by Data66PF** [comment]
Please see our instructions and please put the title to be more clear. All of your titles are not clear as each has just SEO # 1 for example. Please put SEO Publisher as an example for this one. I will leave them open for a week to see if you change them.

**Comment by srikumar101** [comment]
I have edited it Donna
