### ISSUE TITLE
Set an existing photo as Profile picture 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#162]
Hello :) 

it'd be awesome and really helpful if we could set an existing photo as a profile picture instead of needing to upload a profile picture Separately

because members could have duplicate pictures (Without meaning too) 

I'm not sure weather this should be marked as an "Enhancement" or not :)

thank you :)

**Comment by Data66PF** [comment]
We used to have this feature but I believe it didn't work with mass photo upload or caused other site issues.
