### ISSUE TITLE
Option to allow users to disable the "Recently viewed by" 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#167]
Hello :) 

some users dont want to see who they've been viewed by , so an option to allow them to disable the block would be useful :)

**Comment by Data66PF** [comment]
Please post a tutorial for your users for how to set the privacy settings as this setting exists already, in their privacy settings.

**Comment by Lukey199223** [comment]
Ah right :) sorry Donna, didn't realise that was in the privacy settings options aha :) , thank you :)
