### ISSUE TITLE
Please relocate "reply without quote" button at top of thread to just  below center of last thread.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox-feature-requests#169]
This button is in the wrong place at the very top of the thread. Users are most likely to use this button in response to the last reply when they do not want to quote the last thread (perhaps because it is a mile log).

Currently to use this, a user has to first scroll all the way up, and in a lengthy thread, using it can become impractical. This should be a real easy enhancement to do.

**Comment by Data66PF** [comment]
Please post according to the instructions. Things like this that are visual in nature need a visual reference. Show where it is and where you desire it please.
