### ISSUE TITLE
Email: HTML format

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#174]
Dear Team,

Currently emails which are sent out for notifications and other announcements are in plain text with a link. There should be an option to send out HTML format Emails. 

For example when an event is created, Event title, high level description and photo (if added) should be sent out to as email.

**Comment by srikumar101** [comment]
Why rejected :(

**Comment by Data66PF** [comment]
Our lead developer said it would be best for security not to do this. You can get a third party developer for it.
