### ISSUE TITLE
Video time limit for security groups.

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox-feature-requests#176]
Since uploading videos to your site requires Zencoder, which charges by how long a video is, it would be nice to have a max time option for security groups. For example, if free members want to upload videos they can only upload 10 second videos max, while premium members can upload 30 seconds.

**Comment by jhayden2000** [comment]
Hello. Shy did this get a third party dev tag? Did a dev create an app for this?

**Comment by IsabellaJolie** [comment]
Hi jhayden2000, 
It means we will not implement this feature but leave it to third party devs. Regards.
