### ISSUE TITLE
Editor compatibility with Static Page, newsletter, blogs

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox-feature-requests#177]
I know you guys have sen this a bunch of times.. so im not expecting much but i just want to plead my case here. i dont know html code. and the one thing i loved about V3 was that it didn't force me to learn a new language in order to use it.. I could create a newsletter in a word doc and paste it to a newsletter or even make a blog and it was simple... The v4 editor obviously doesn't do that and its quite uncomfortable for me. Others have complained about this as well as it is a functionality that alot of us relied on, so im just hoping to put his back in your radar.

**Comment by Data66PF** [comment]
please read our instructions as it says one topic per request and you have newsletter, blog, etc. Note that this request really should be in the feature requests for third party developers as we won't be doing any editors for security reasons. https://community.phpfox.com/forum/search?forum_id=122&search%5Bsearch%5D=editor&search%5Badv_search%5D=0&search%5Bresult%5D=0
as it is already there in a few requests, just comment in the one that looks most appealing so a third party developer can make this if they see enough interest.
