### ISSUE TITLE
send message option

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox-feature-requests#181]
there is no 'send message' button while sending message, messages are sent on pressing "enter", it would be great if  this can be customized.
Thanks a lot.
![message send option](https://cloud.githubusercontent.com/assets/13433124/16835541/d40ffe92-49d6-11e6-9344-038605629165.png)

**Comment by Data66PF** [comment]
Please search before posting.

**Comment by SalmanKhan86** [comment]
pls provide me link where it is
