### ISSUE TITLE
Chat / IM - Enhance it to group chat

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#183]
Dear team, 

Chat/IM is a very good feature. It would be great if we can enhance its capability to add people in a group to chat. 

Requirements:

1) Users can create multiple groups and add people in their friends list to the group. 

2) People who are added will get instant notification on addition to the group and everytime someone pings in the group.

3) Users should have an option to disable notification or mute it for a particular group. 

4) Users should be able to leave the group. 

5) Users who are added who be able to add other friends in their own friend list. 

6) Users can share links (that generates thumbline) and photos

**Comment by Data66PF** [comment]
We want this area for small improvements, not big things. We already have this list on our internal list of possible improvements though. However, your multi-item feature request needs to be in the community feature request area for bigger requests.
