### ISSUE TITLE
SEO - Change default username

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#186]
Dear team,

Since it impacts SEO if the default username is like "profile-123" can we change the default username to be <FirstName><LastName><RandomNumber> ?

Regards.

**Comment by Data66PF** [comment]
This is already in the script. Change it as per this tutorial, https://store.phpfox.com/kb/article/631/how-to-enable-vanity-profile-urls
You will want your users to change their username if you didn't have it set.
