### ISSUE TITLE
Friend request

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox-feature-requests#188]
in friend request when i got many request i have to accept it one by one.when i accept one request pop up box disappear and a message box comes with confirmation. if this is doing such a way that i continuously click on all requests one by one. it would be better that pop up box not disappear any way.
![friend request option](https://cloud.githubusercontent.com/assets/13433124/16941122/d28459be-4dab-11e6-8a52-edf368ccae31.png)

**Comment by SalmanKhan86** [comment]
Friend request style in fb. i can accept all my friend request in one window quickly and easily.this is better User Friendly.
![frieend request style](https://cloud.githubusercontent.com/assets/13433124/16945492/e6be2a88-4dc2-11e6-99ef-1df62a28f166.png)

**Comment by Data66PF** [comment]
Search before posting. https://github.com/moxi9/phpfox-feature-requests/issues/12
