### ISSUE TITLE
A Location feature

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#192]
Hello :) 

I now viber used to have a location app,

but I think its an essential part of social networks these days to have a "Location" feature on the status bar, where you can add your  location to your status, photo or video

The location feature should be like facebook's, where you can type in any custom location 

I Know We're trying to take phpfox down a different road so its different to facebook, but some of facebook's features are a must have :)

**Comment by Data66PF** [comment]
Checkin already works. You can already input your own location. It might be bugged if it is not working for you.
