### ISSUE TITLE
Sharing a youtube link on stus publicly

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#193]
I'm surprised that in v4.xx there is no way to publicly share a youtube link via the site in order to gain more traffic like in previous version. So being able to share a youtube video link encapsulated in the phpfox site. Consideration of how to draw in traffic should always be considered in implementing all features of the site.

**Comment by Data66PF** [comment]
You can to this already. Just enable the video app or just copy and paste the video into the status share.

**Comment by prepperz** [comment]
If you paste the video link in the phpfox status, there is no link to that status that can be shared on facebook for example.
