### ISSUE TITLE
Video blocks

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox-feature-requests#195]
I looked today in order to make a block for my videos, but i dont see any in the blocks section. this would be nice to have block options for videos.

**Comment by Data66PF** [comment]
Please see our instructions and put more details. This is incomplete.

**Comment by jhayden2000** [comment]
Im not sure how much more clear to be so i will show photos.  Here is the block section. There is no way to add blocks to the video page. . Also you cant create video blocks on other pages.
![screenshot_2016-07-25-12-57-51](https://cloud.githubusercontent.com/assets/20259022/17109902/fea33fe0-5267-11e6-80bf-ee89bc8b094c.png)

![screenshot_2016-07-25-12-56-44](https://cloud.githubusercontent.com/assets/20259022/17109913/0a3e8ee0-5268-11e6-83da-fa0387b7fdb6.png)

**Comment by Data66PF** [comment]
The video app is an app. In order to add blocks, you need to code them as another app. https://docs.phpfox.com/display/FOX4DEVDOC/Apps

Other devs are already making apps for video blocks. As such, we cannot do this as there are apps and themes for it already.
