### ISSUE TITLE
UserName in Profile page

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox-feature-requests#197]
its would be great if we have user username in profile timeline page.username means mysite.com/username. it can be included under user full name.
![user name in profile](https://cloud.githubusercontent.com/assets/13433124/17091950/7e631aa4-525c-11e6-9a0b-19c87aec5091.png)

**Comment by Data66PF** [comment]
I am not fond of this as it can allow easier hacking to see the username that someone logs in with.

**Comment by SalmanKhan86** [comment]
i am meaning to say this username which one can easily get when someone visit your profile.
![username v4](https://cloud.githubusercontent.com/assets/13433124/17125830/a4d91248-5314-11e6-8a21-765962d4d426.png)

**Comment by Data66PF** [comment]
I see it in the url. It has always been there. However, posting it where it's easy to see and grab is not ideal.

**Comment by AndriiLazko** [comment]
Hello, @SalmanKhan86. Our team has already developed app which you were asking for. Please use it for free. https://store.phpfox.com/product/1627/username-on-profile

**Comment by prashok27** [comment]
app not working with Material template. kindly help.
how to modify.
