### ISSUE TITLE
Thumbline of link posts

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#202]
Dear team, 

When a link is posted or shared as a status update or on pages or groups or even in comments, it will remain as a static link.

Instead it should generate a thumbline of images or videos from the source link.

**Comment by Data66PF** [comment]
We already have an url grab. I am not sure of what you mean for this request. Please test at our demo and please provide a link to your tests so we can see what you are trying. Screenshots help as well, as our instructions for posting a feature do say to include.

**Comment by srikumar101** [comment]
Sure Data.. I shall test the URL grab feature.. Thanks
