### ISSUE TITLE
News feed and page feed should be configurable

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#203]
Dear Team, 

We see lot of updates on news feed, for example "ABC is now friends with XYZ" which not everybody may be interested in.. 

Can we have an option to configure this from AdminCP. For example, Show/Hide "Now friends with"  update on news feed, similarly Show/Hide "Started a forum discussion", Show/Hide "created an event", Show/Hide "Going for an event" etc.,?

**Comment by akvaskov** [comment]
Why don't you want to add this option as a default feather of the PF? Your competitors have it.

![ning](https://cloud.githubusercontent.com/assets/18528411/17259401/f75c7c0a-55d3-11e6-8d7d-c8e09c51a2d3.png)

**Comment by akvaskov** [comment]
As I understand, there wil be no reply :(
