### ISSUE TITLE
Option to control Video Dimensions

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#207]
Currently, the videos are being displayed full page by default and no way to control the demension. To reproduce:

    click on main video link in menu
    click on a video

99% of the time, people don't want a full page video by default, so give the user an option to display the size or for the admin to set the default size (via specific demensions or % of page) would make it user friendly instead of just shoving it down their throats because that is what it is like when there's no option.

**Comment by Data66PF** [comment]
Are you speaking of mobile?

**Comment by prepperz** [comment]
No I mean in the regular web browser. Not everyone wants a video to take 90% of the web page. If the user want a bigger video they can simply expand via the video itself.

**Comment by Data66PF** [comment]
https://v4.phpfox.com/v/play/35/ I don't see any issue with it. It has the menus to the left and is not taking all the page and I'm on a notebook computer.

**Comment by Data66PF** [comment]
This seems like something that won't benefit many and would be best as a customization.

**Comment by prepperz** [comment]
Wow. You're making a big assumption.  So when a add a video is added and it takes up almost an the entire page real-estate and this should be for 3rd party devs? unbelieveable.  If you look at any video site youtube, vimeo etc... even socieal nets like Facebook and others. When you add video to any of those sites do they take up 80-90% of the screen real-estate by default?

Whatever happend to the old phpfox experience? There is a reason why hardly anyone post any bug or feature request anymore. Most likely its because they feel that after so many posts and so many years that it's not worth the effort any more because everything seem to drift away from creating something a with a friendly user experience. 

Though phpfox is using the latest tools,  it has lost its spark. Just like many movies that come out these days with the latest special effects, but they are all mostly crap their is no substance and the story telling suck.  This is what phpfox feels like these days compared to it's vibrant life back in the day. 

I've been a long time phpfox supporter, but now it's just bleh... Let's see that spark again shall we?
