### ISSUE TITLE
More control system

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox-feature-requests#21]
More control system for site-wide.

Like as for IM app: Admin can't see/control the conversations between users. I'm getting lot of rapports for disturbing conversation from users via mail but i can't see the conversations.

**Comment by Data66PF** [comment]
This is too vague. If you would please put it as we mentioned in the community thread, https://community.phpfox.com/forum/thread/54178/core-improvement-feature-request-area-open/ . Please put only one thing you want in the request and please have the title be more clear.

**Comment by Data66PF** [comment]
We can reopen this one if you edit it to include the info we need.
