### ISSUE TITLE
App Version add-on Updates section like firefox

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#210]
Currently, it is very difficult to findout which version an app is that is installed on your site because the information is not always included. It would be nice if phpfox has a feature of something similar to firefox in which it has an inventory of apps that are currently installed and their version number and whether there are new version available for updates / remove / disable which you just check off from the store.

**Comment by Data66PF** [comment]
We do have this feature already in the app itself as long as the developer put the code to show it. If you click an app, and if the developer put the code, then you can see if the app has an upgrade available. The app also shows its version at the bottom of the app view, by default.

**Comment by Data66PF** [comment]
We are looking at ways to improve this.

**Comment by cespiritual** [comment]
About this request I think would be nice to have a block on admincp dashboard to show the apps that have updates. I know that this info is on the apps page, but admins don't go often to this pages, but they go to dashboard everyday.

**Comment by PhpFoxJohnJr** [comment]
Just wanted to add here that the date last update should also be added.  I would waste too much time comparing version numbers...not saying it shouldn't be there as a backup to be positive that you are upgrading but having the date last updated, I can just look at the page and if it says update several months ago...I would not have to check the app version.  Thinking out of the box to be more efficient.   Although Cespiritual idea is even better.
