### ISSUE TITLE
hide anyone’s post 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox-feature-requests#213]
there is great if a option is available so that users can hide anyone’s post if he can't like post.he can hide it from their timeline only. this post is still visible to everyone but not to users who hide it.

Thanks a lot

**Comment by Data66PF** [comment]
With our upcoming improvement to the blocking feature, would you still want this if the user can already block the other user's content from showing to them?

**Comment by SalmanKhan86** [comment]
blocking user and blocking user content is different things.i just want to block user particular feeds not whole user if i don't like it.

**Comment by Data66PF** [comment]
I'm not sure about this request in regards to our core product as it will add weight/load and we just optimized everything. I'll see what Ray thinks when we are looking at features again.

**Comment by SalmanKhan86** [comment]
in fb we can hide post in this way.
![hide post feature](https://cloud.githubusercontent.com/assets/13433124/18025468/4f65e8b6-6c48-11e6-89cd-03215af8c0e3.png)
