### ISSUE TITLE
Encapsulate all shareable links in a phpfox page so it can be shared on other sites to bring in traffic

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#214]
#Links in statuses cannot be shared on other sites...  This needs to be shareable, this way it can be shared on Facebook or any other sites which could then bring traffic to owner of a phpfox site and once the visitor is at the phpfox based site can then click on the link to go to the source. 

This has been requested in the past and everytime a newer or major version update of phpfox comes out, it forgets all the basic feature goodness past features. It's that people need to request the same things over and over for as long I've been using phpfox since the early days.

Please always keep in mind that everything that is shareable should have it's own page or link on the phpfox site so that it can bring in traffic from other sites. In future designs or feature always keep in mind, "how do I bring in traffic from this feature?"

**Comment by Data66PF** [comment]
Please search before posting https://github.com/moxi9/phpfox-feature-requests/issues/191
