### ISSUE TITLE
Blog Image Link Show on the Blog Index and News Feed

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox-feature-requests#215]
Hi, Since you build this V4. I'm still waiting to improve the blog page. This image link is messing up the blog main page and for me this is not good to show the image address on public.

![](https://cloud.githubusercontent.com/assets/16037019/17566665/03847512-5f45-11e6-85eb-c404ef4479b9.jpg)

**Comment by Data66PF** [comment]
Interest to strip out the img tags from showing - just hide the entire line of code there and start the preview text at the text line below the img code.

**Comment by juniortimeline** [comment]
I hope this is one of the priority on the next build. Thank You

**Comment by juniortimeline** [comment]
Any update for this request? Thank You

**Comment by Data66PF** [comment]
Please do not keep posting in this. We mark them interest so that next time we are looking at features to approve, we look at these. We already have our feature list for 4.5. When we are looking again, we will at that time update this with accepted or rejected once our core developers have a look.
