### ISSUE TITLE
Replace video source

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#217]
From time to time the video source goes bad or are removed by youtube or its authors.  As a result, the pasted in Youtube source is no longer good on the php site. If you delete the video on the phpfox based site, any inbound links to that video will be broken 

Unfortunate you can't edit and replace the source, so it would be nice to simply replace the source so the inbound links will still be good.

**Comment by Data66PF** [comment]
Please detail this feature more. Does the new replaced source grab a new video? Is this restricted by user group?

What prevents someone with an approved video to then substitute a bad video in its place?

I don't think this feature would be beneficial due to the various implications.

**Comment by prepperz** [comment]
Your argument is not very good whether if it's beneficial or not, That's like saying sites shouldn't be allowed to edit their status.  That's up the site owner to decide whether it is or isn't and it holds true for video source.

What's important with a video link on a phpfox site is a few important factors. SEO, marketing, sharing etc...   all these require that the link remain the same. S0 imagine you any of the previously mention and then video is no good on that link, so that makes that a broken link. Not good.

So yes, when the source is replaced it should grab the new video, but the link should stay the same and should allow the admin to restrict by group or not at all.
