### ISSUE TITLE
online notification

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#218]
Currently there is No online notification after the 4.4.1 b2 update. 

if you:
post on your status.
on another browser with a different account, like and comment on the status.
go back to the first account.
now go around the site click on any site link, you'll notice there is no red notification until you refresh.

Having a functional online notification would be nice because no one goes around a site hitting refresh all the time. We had this in previous versions.

refer to issue: https://github.com/moxi9/phpfox/issues/1630

**Comment by Data66PF** [comment]
Was fixed in 4.5
