### ISSUE TITLE
Need To have TOOLTIP

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox-feature-requests#221]
we don't have any option for define tool tip for like,share,report and many other options.
Thanks

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox-feature-requests/issues/7
and 
https://store.phpfox.com/product/1118/tooltip-advanced-cespiritual

Please note that we already have interest in the one github request. 

Please note that "many other options" is too vague as per our posted feature request posting requirements.
