### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox-feature-requests#228]
Hello,
1) Please make it so that the notification messages about that the user is written in "IM messengers" would come to his e-mail when he is not on site.
2) Make a pop-up sound notification to the user about some event (sample pictured).

![notifications](https://cloud.githubusercontent.com/assets/15389101/18577284/2ca72a52-7bf1-11e6-9851-fb766d1b0cbf.png)

**Comment by Criotin** [comment]
![notifications 2](https://cloud.githubusercontent.com/assets/15389101/18577302/5383c040-7bf1-11e6-97eb-358decc0c799.png)

**Comment by Criotin** [comment]
What does it mean "Third Party Dev"?

**Comment by Data66PF** [comment]
We will let third party developers do this as an app. There are too many things to consider with something like this and the amount of mail going from client sites. This is not something that would benefit a high percent of clients so needs to be a third party.

**Comment by kirkkhua** [comment]
@Criotin you may try [Desktop notifications for phpFox](https://store.phpfox.com/product/1142/desktop-notifications-for-phpfox)
