### ISSUE TITLE
User's full name arrangement

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox-feature-requests#23]
User's can enter their name with all uppercase or lowercase or any special characters.
Can you do anything for this like as Facebook or Twitter?
Than we can get clean and regular community.

**Comment by Data66PF** [comment]
As we said in our post for how to post a feature request, please do not use "just like facebook or other site" when describing. We need a full description or we will have to reject the proposed feature. Please read our instructions for posting a feature. Thank you.

**Comment by Data66PF** [comment]
We can reopen this once you edit it so we know what you want.
