### ISSUE TITLE
Advertising ads

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox-feature-requests#230]
Hello,
1) Why is it impossible to see the image of the advertising ads of users in the admin panel?
The image may contain illegal illustrations.
Please make the opportunity to view the advertising image in the panel.
2) Please make it so that users have the possibility to choose between CPM and the PPC, when placement of advertisements.

**Comment by Data66PF** [comment]
This has more than one request. Our posted instructions state to have one request per feature.

**Comment by Criotin** [comment]
I'm trying to help you to improve your product. Instead of thanking you close my suggestions.

**Comment by Data66PF** [comment]
Please read our instructions for posting feature requests. We reject when they don't follow the posted instructions.
