### ISSUE TITLE
Mail module

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox-feature-requests#231]
Please do function so that users could add pictures, files, links and emoticons.

![mail](https://cloud.githubusercontent.com/assets/15389101/18756371/64722368-80f8-11e6-8eee-206bd38f0c74.png)

**Comment by Criotin** [comment]
Why is it closed?

**Comment by Data66PF** [comment]
We marked it for third party as this is better for a third party to make and there are already apps for this or that those developers could improve if you checked with them.

**Comment by Criotin** [comment]
Point to the module, which will add to the message links, smiles, files and images.
