### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox-feature-requests#232]
Make a table "phpfox_log_session" would be automatically cleaned, as over time it begins to weigh a lot of megabytes.

**Comment by Data66PF** [comment]
There are other tables that go with the log_session. You would be best to read the forum thread for that and be sure to remove all of them too. 

We will consider this feature though.

**Comment by Data66PF** [comment]
https://community.phpfox.com/forum/thread/44988/is-it-safe-to-empty-log_session-table/

**Comment by neil96** [comment]
This feature exists. But to make it works, you have to setup cron job.
