### ISSUE TITLE
Users online

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox-feature-requests#233]
Users never click to "log out", they just close the tab. The timing has to go, not when a user clicks on the "log out", but when the user has ceased to carry on activity on the site.

![user online](https://cloud.githubusercontent.com/assets/15389101/18768413/a5a3a02a-812d-11e6-9587-a2e7965d171b.png)

**Comment by Data66PF** [comment]
Have you set the setting:

Active Session

Define how long a user is displayed as active on the site in minutes. 

If a user is inactive longer then the specified setting they will be removed from the online session table. When this is done they will no longer appear to be online when other members view their profile. If the user suddenly becomes active after their session expired a new session will automatically be created.

**Comment by Data66PF** [comment]
Oh I see your request is for the online popup. That would be a different setting, yes. We can look at this to add the setting to also include the popup status.

**Comment by Criotin** [comment]
![active session](https://cloud.githubusercontent.com/assets/15389101/19238136/c7b7be9c-8f08-11e6-9053-cad178b5aff5.png)

**Comment by Data66PF** [comment]
I already answered above. Thanks.

**Comment by neil96** [comment]
@Criotin You have to setup cron job for delete old session.
