### ISSUE TITLE
Downloading apps when necessary

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#239]
I like the store set-up, but it doesn't have the option to download the apps the have been purchased. There are some instances when we need to work on an app when either the dev  cannot be reached, MIA, or something that needs to be fixed right-away. 

So having an option to download it would make it convenient if the need ever arises.

**Comment by Data66PF** [comment]
We don't be doing this due to the store is to prevent piracy.

**Comment by prepperz** [comment]
What this says then is that phpfox operated site are left at the mercy of the developer. So if the there are issues with the app and the never responds or cannot get a hold of them we are supposed to just leave the broken app? 

That isn't right. Especially if we paid for it.  An prime example is phpfoxmods. People that have legit licenses shouldn't be punished because of a few bad apples. If the pirates wanted bad enough they're going to get it regardless.
