### ISSUE TITLE
Transferring Apps license Between Sites

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#240]
I have multiple sites, it was really convenient to be able to transfer App licences between sites. Currently, the store doesn't have this option.

For example, some times we buy apps and later we want to use it on a different site project that is more appropriate. 

It would be really nice to be able to do this without going through any hassles.

**Comment by Data66PF** [comment]
This is not something we can consider. The apps are licensed to the license id and key. If you change your domain, it will still work on the new domain.
