### ISSUE TITLE
Complete Uninstall of apps from store

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#242]
Some apps purchased from the store does not completely uninstall and are left with an a big blue "install" link that is clutter up the dashboard. Please include a complete uninstall option.

**Comment by Data66PF** [comment]
You should encourage those developers to make them in v4 native instead of porting their v3 modules. Only the v3 modules do that. 

We do have plans on some improvements but this really is on the developer to make their apps v4 native rather than old v3 style.
