### ISSUE TITLE
Support hooks for user notification and friend request

### ISSUE THREAD

**Issue by Phong-YouNet** [moxi9/phpfox-feature-requests#245]
On our Mobile Application, we'd like to send push notifications when users have notifications and get friend requests but there are no hooks for us to use at current. So in order to push a Notification, we need to override some files in core as on friend and notification.

These hooks will be needed in many 3rd-party apps and we hope that these hooks will be supported in phpFox Core in soonest.

**Comment by Data66PF** [comment]
This needs to be submitted in a ticket to our core developers please, for faster implementation.
