### ISSUE TITLE
Delete option on Pages is unclear 

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox-feature-requests#25]
_From @lueung on February 18, 2016 15:22_

The delete option on Pages (the upper right gear) is unclear whether it is to delete the page or photo image.

_Copied from original issue: moxi9/phpfox#1144_

**Comment by Data66PF** [comment]
The Change Cover is for changing and deleting the cover. The delete button is to delete the page. In the future, please post feature requests in the new feature request tracker for small improvements like this. I'll move this one.

**Comment by optiroot** [comment]
I solved this by just changing the phrase to "delete page" instead of just "delete"; so it can be easily fixed.

**Comment by Data66PF** [comment]
That's a good idea @optiroot

**Comment by Data66PF** [comment]
In photos, we show "Delete this Photo". I think we need to be uniform throughout the site. We should say "Delete this Page".
