### ISSUE TITLE
Documentation/Guidelines about JS events supported by platform when loading pages via ajax

### ISSUE THREAD

**Issue by Phong-YouNet** [moxi9/phpfox-feature-requests#250]
Our phpFox apps need to catch JS events (such as on domready, on resize, etc.) to initialize or do their specific functions. 

Do you have any documentation/guidelines about JS events supported by phpFox when loading page via ajax request?

**Comment by Data66PF** [comment]
Please ask in the forum. This area is only for script feature requests. https://community.phpfox.com/forum/130/coding/ you can ask coding questions there.
