### ISSUE TITLE
Active load makes clicking Ad link on footer almost impossible.  Make header & footer stationary.

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#258]
The combination of the actively continuous page loading make it counter intuitive and very difficult to be able to click on the advert link.  It would make sense to make header and footer stationary.  This will solve a lot of issues.

**Comment by prepperz** [comment]
When an legitimate issue is raised, you simply close the ticket without explanation or discussion? No wonder people are leaving phpfox.

**Comment by neil96** [comment]
Your request is good, but this is a layout feature. It can be created easily from a 3rd theme/app. Even, you can do it by adding css in manage theme.
