### ISSUE TITLE
Private Messages on new line

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox-feature-requests#26]
As said in #22 I think will be better to enable private messages to be on new line, that's because so much clients ask this and it could be simply achieved by placing a button!
I'd like to see this and I guess so much other clients too.

**Comment by Data66PF** [comment]
I like this idea too. How many times have I sent a PM message when I meant to just go to a new line, and then had to send another pm with the rest of the message? I cannot even count how many I have sent like that and also received. Enter button is not good as a submit button in private messages.

**Comment by Spaninet** [comment]
This is a must.

**Comment by Data66PF** [comment]
There is a free app for this already. https://store.phpfox.com/product/944/shift-enter
