### ISSUE TITLE
Market place item pictures looks weird ?

### ISSUE THREAD

**Issue by maniacscorpio** [moxi9/phpfox-feature-requests#262]
If we enabled Bundle JavaScript & CSS Market place item pictures looks weird ?  Seems Bundle JavaScript & CSS causes conflict in CSS/JS.. 

http://i68.tinypic.com/2wowx7c.jpg
![mnmn](https://cloud.githubusercontent.com/assets/23141922/19913332/ab393d38-a0c7-11e6-82c6-6a1c5e272ac2.JPG)

**Comment by neil96** [comment]
This is feature request repo, but your issue look like a bug. Next time, please post on our [bug repo](https://github.com/moxi9/phpfox/issues).

Btw, our marketplace on 4.4 doesn't support html, but on your screenshot have html.
