### ISSUE TITLE
Profile Photo on user dashboard  

### ISSUE THREAD

**Issue by erick260** [moxi9/phpfox-feature-requests#264]
#I've been wanting this feature for a long time now. I've been trying to add it, but no luck yet. I I would Like to place the Users Profile Photo on the Main Dashboard. I do have a screenshot as an example. 
![new](https://cloud.githubusercontent.com/assets/19263189/20032194/9c377d22-a35b-11e6-9fcb-0d221d6a8a03.png)

**Comment by neil96** [comment]
Thanks for your suggestion @erick260 ! But this is a layout feature, it can be completed very easy by a 3rd-party app/theme.

**Comment by kirkkhua** [comment]
@erick260 there is an app called [User Dashboard](https://store.phpfox.com/product/1721/user-dashboard) that may help you
