### ISSUE TITLE
message center on dashboard 

### ISSUE THREAD

**Issue by erick260** [moxi9/phpfox-feature-requests#267]
it would be cool to have a message center under the profile photo as stated in my other ticket #264 

  this will make it more user friendly. Also most popular sites such as myspace had this exact feature 
![messages](https://cloud.githubusercontent.com/assets/19263189/20032294/dfa8d5ae-a35d-11e6-96fa-01fbe8212c9e.png)

**Comment by neil96** [comment]
By default, we don't have this block. Which version are you using?
