### ISSUE TITLE
View source on webpage reveals phpfox. It shouldn't be that way.

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#286]
Prior to v.4.x.x, a website visitors used to not be able to tell a site is run on phpfox. Bring this back back. There should not be any indicator that it's a phpfox site.

**Comment by neil96** [comment]
We don't understand, could you tell us detail.

**Comment by prepperz** [comment]
Go to the homepage and right click on browser and view source. Control-F then search for phpfox. 

There are 14 instances that says it is a phpfox site. People should not be able to see any evidence that it's a phpfox site in the view source.

In v3.8.x, this was one of the very important aspects of the script.

**Comment by neil96** [comment]
Duplicate with #285
