### ISSUE TITLE
The text's display in post

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox-feature-requests#292]
Make it so that the text would be displayed not in full variant, and would be hiding under the button "Show more".

![default](https://cloud.githubusercontent.com/assets/15389101/21014070/83b44452-bd6d-11e6-888c-5867b34403a4.png)

**Comment by IsabellaJolie** [comment]
Hi Criotin,
Currently, the newest version of phpFox do not show the full text as your screenshot. You can check it on our demo https://v4.phpfox.com/. Regards.
