### ISSUE TITLE
Choosing usergroup on signup

### ISSUE THREAD

**Issue by shashankguitarist** [moxi9/phpfox-feature-requests#301]
Allow users to choose user group (profile types)  on registration . ( this can be done with membership but if we choose it to be free , members can change their usergroups from their profile anytime..

**Comment by neil96** [comment]
This feature is available if you [enable subscription on](https://docs.phpfox.com/display/FOX4MAN/Enabling+Subscriptions). Then, you create some free packages and add them to signup.
