### ISSUE TITLE
Pagination for pages

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#31]
It was mentioned that there is already a pagination request somewhere, however I do not see it anywhere so I'll request the pagination for pages. Over 90% of my users found the current pages display to be a bit confusing and they think that the page they create have disappeared and end up creating another page.  Even I was a bit confused in how it worked at first as well so there is definitely a need for pagination in pages.  

When they click on pages from the main menu and it only show 10 by default with a drop-down that shows a max of 20. This is the area where they are thinking, "hey where did all pages disappear to?"

The other area of confusion is when they click on the categories and then it only shows 10 so it looks like there's nothing more after that because there's no indicators that there anymore pages so they don't scroll down. Now if they don't have prior knowledge to scroll-down they won't because it looks like there nothing more there to see. So a pagination here will also help or @ the very least instruction that tells them to scroll down for more if there is more to load.

**Comment by lueung** [comment]
So here is the latest question comment from one of my users today: " BigJ	
Hey anyway we can get more crypto/communities to show, Heck I click 20 and Netcoin dont even show lol Some folks might not know its even here or think the 10 it shows is all there is."

my response
12 minutes ago
Crypto-city	
"Yes. the main area only shows bits from each category very much like an overview. Click on "crypto communities (all crypto related) then simply scroll down to see more. Pagination is on the todo list to make it mmore intuitive :)"

**Comment by Data66PF** [comment]
We actually need pagination all over the site. Not just in pages but in photos, blogs, etc as loading the pinterest style will not work for large site with thousands of blogs, photos, etc as some of our clients have said. It is locking up mobile devices when scrolling down the unending content.

**Comment by Data66PF** [comment]
Accepted to add pagination to the site that would be an option for admins to choose

**Comment by neil96** [comment]
After review this issue carefully, we figure out that "Paging" should not be consistent with the rest which we use "Load More" style. Therefore, we reject this feature request at this time.
Once we change to "Paging" we have to change the whole phpFox "Paging" style, which is very costly. We'll let you know if this big change is approved in next version.

**Comment by HankBrown** [comment]
I have done a test conversion of my site.
It is not possible to reach the footer on the blogs page.

It's like playing a game. You want to get to a footer link? Yes here it is, see, whoops there it goes again. You've just chewed up more wifi downloading stuff that is preventing you from getting to the footer. That's going to aggravate users. It sure aggravates me.

Essentially the footer is a non-reachable block on the page (which cannot really be called a page, as it is more like a ticker tape).

I've argued for paging before, it has advantages over infinite scrolling. My vote will always be for paged content.

If you must use infinite scrolling, do not use footers, or invent a way to jump to the footer.
**Avoid aggravating users. Do not make them play games they cannot win.**

**Comment by prepperz** [comment]
It seems the original phpfox is no longer and I believe younet running it now. I think and if you dealt with with when giving suggestions, I understand your frustration. You'd think that they'd want to build a user friendly product, but their action says otherwise.

**Comment by phpfoxaccount** [comment]
@prepperz Kindly check our policy at https://github.com/moxi9/phpfox-feature-requests . We publish github for feature request and bug report, for everyone to contribute. We have policy to keep things professional. Please do respect the rule, otherwise we reserve our right to remove your message. 

@HankBrown we understand the issue. phpFox has a setting to restrict the number of auto load and "Read more". We also explained quite clearly. Rejected doesn't mean we would not implement this in future, but in the mean time.
