### ISSUE TITLE
Option for Admin to Disable removal of pages when user account is removed

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#33]
Currently, when a user is removed all the attached pages to that account is also removed when the user is removed. So for example: if a member created hundreds of pages and that member is removed, all the pages are also gone.  This could be a staff, a regular volunteer user etc... 
So if pages are abandoned someone else should be able to take it over or reassigned.

The admin needs to have an option be able to disable the removal of pages when the user account is removed either by the user themselves, the staff or admin. My site is highly focused on pages creation and forums so the option for content not to be deleted is extremely essential.

**Comment by Data66PF** [comment]
I don't agree with this one. When someone leaves, such as we delete a spammer, I want all content gone. My sites have user cancel disabled and they have to contact me for removal. If they have no content, I delete. If they do, I change their details and remove personal things but I keep their blogs, forum stuff, etc.

However, in the past, clients wanted a way to choose what content remains when a user cancels. For this request, I suggest changing your request to be for an option for admin to set whether content is deleted when an account is deleted.

**Comment by lueung** [comment]
OK I updated the info. Whether it's agreeable is not really relevant as each site owner run there site for different content and purpose. What's important is having the option to not remove the content. One of my staff decided to see what happens if he deleted one of his accounts and all the pages he created was gone.
