### ISSUE TITLE
Auto Detect Users Language

### ISSUE THREAD

**Issue by Ramstete** [moxi9/phpfox-feature-requests#34]
Hello, is it possible to add this feature back in phpfox V4?

I post here the link to the old v3 option
[V3 KB about auto detect users](https://store.phpfox.com/kb/article/333/auto-detect-users-language)
 or like this or auto detect by browser language

**Comment by Data66PF** [comment]
Before, we had issues with this not working as many disable location services and use private browsing. As this uses the browser language, we had complaints. If we enable this again, clients would need to be aware of those restrictions as we can't work around browser privacy.

**Comment by Ramstete** [comment]
wonderful, in the globalization era, where geolocation geofencing and so on are the trend for bilion of people, we go back in the past... Better have an option more to disallow than an option less to allow.

**Comment by Data66PF** [comment]
IMO, this would be better as a third party app because a third party can keep up with newer technology for it and with a script as large as we have, there are things like this that are best served by external parties.

**Comment by Ylmzef** [comment]
:+1:
