### ISSUE TITLE
Landing Page for Pages

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#37]
I find that the "home" default landing page for pages is not always appropriate depending on the community and content. It would be make the pages section more user friendly if the pages founder/admin can set the landing to default to any one of the tabs, whether it be "info, forum, home, photos, events, or widgets that are created.

People will definitely get more use out of this flexibility.

**Comment by Data66PF** [comment]
This was a setting in V3. It might be good to enable it if there's enough interest.
