### ISSUE TITLE
Admin Option to Control how internal links open

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#39]
Currently phpfox by default opens all posted links in a new window whether it is internal or external. 
The problem is the user ends up with a bunch of new windows. This can get rather annoying after a period of time.  

It would be really convenient and more user friendly there is an option for the admin to control how internal links open. For example, I want all internal links to open in the same window unless specified otherwise in a tag.

**Comment by Data66PF** [comment]
The request is to allow admin to choose if internal links open in same window. We will look at that part of this feature request and not the second part of allowing each link to be specified whether it opens in same or other window.

As this could be too much of a change, I'll wait for Ray to see this one.
