### ISSUE TITLE
Ability to edit status post

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#40]
I find it really inconvenient that I have to delete the entire post just because I needed to correct a spelling error. What's worse is that if someone already commented on your status and you delete the post you kill the entire conversation. So having the ability to edit status post would be awesome.

**Comment by Ylmzef** [comment]
:+1:

**Comment by Data66PF** [comment]
I like this idea and have thought all along that we should have it.

**Comment by neil96** [comment]
Like too.

**Comment by aakash83** [comment]
:+1:

**Comment by Lukey199223** [comment]
This would be awesome :) , I've actually got this on my custom list,so knocking stuff off my list is always a good thing :)
