### ISSUE TITLE
Better core WYSIWYG for Blog, Forums or wherever it is appropriate

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox-feature-requests#41]
The WYSIWYG in its current form is pretty non-existent. Having a robust (or at the very least just the basic essential) core WYSIWYG tool will be very valuable in helping to generate quality content that is easy to use for everyone. Especially for those who are new.

**Comment by Ylmzef** [comment]
:+1:

**Comment by Data66PF** [comment]
This is a feature best done in an external app by a third party developer as these tend to allow hacks easily and so the security needs to be fully updated each time any vulnerabilities are found. We don't need to take from third party developers.

Though I, myself, really need an editor for my author site if I upgrade it to v4, this feature is not something we can do within the core as it is too big and involved. Please post this in the community if it was not already posted but I do believe it was.
