### ISSUE TITLE
Improved Core forum management tools for pages

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox-feature-requests#42]
I am not sure if the current pages forum re-use the codes from the main forum, but both lack the ability to organize the threads in a certain order. So discussing topics become totally disorganized.

The pages forum also lack the ability to create categories as well as not being able to move threads.  So this would make the pages forums more usable.

**Comment by Data66PF** [comment]
We allow only one request per feature request. Please separate your requests. If you want the main forum updated with small improvements, each one needs to be a separate request.

If you want pages discussions to have features, each one needs to be separated.

If you want to add categories to pages discussions, it needs to have its own request.
