### ISSUE TITLE
Site admin account should be able to use use Pages forum Thread Tool for any pages

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#43]
Currently, the site owner admin account cannot use Pages forum Thread Tool to manage the forum unless site owner is admin or founder of pages, but instead is only presented with a subscribe option.

As a site admin, It would be nice to be able to use the thread tool to manage any pages you want.

**Comment by Data66PF** [comment]
Please post more details.

**Comment by Data66PF** [comment]
This feature, since not described, we will accept as follows:

If site admin needs to manage a Pages Discussion, he should be able to do so without being pages admin. This is for the Pages module only. Not for groups app.
