### ISSUE TITLE
Extra Claim Button when using previous suggestion/fix by data and fix #966 

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox-feature-requests#5]
_From @PhpFoxJohnJr on February 5, 2016 16:45_

I have been using Pages Mini Menu since 4.09 suggested by data which fix the missing Claim button as well as the share button.  Now in Fix #966 they added another claim button in this latest fix so now I have a claim button and a like button on the bottom right corner of the cover image and for my site I also have in block 1 I have Pages Mini Menu which consist of "Share" and another claim button. So I have two claim buttons on one page.  I could disable the mini menu but that would take away the share button.

Maybe this could be fixed later on...no rush but although it looks nice having the claim button on the cover image it is only going to be click one person one time so why cover even a small portion of the image for something that may or may not be ever click or needed. I still want it on the page but it should be on a Pages Mini Menu like you have it where claim, share and report should all be. By the way where is the report button...did we ever have a report button on pages?

_Copied from original issue: moxi9/phpfox#1081_

**Comment by PhpFoxJohnJr** [comment]
I know this is an enhancement in phpfox thinking but please remember the choice now is either you can have...
The main claim button on the image (which will only be used once...seems like wasted space) and then** not having the share link or the report link**.
Or
Have the first claim link, the second claim button, a share link and a report link.

**Comment by Data66PF** [comment]
Do you have any sort of screen shot? I got confused with your last comment :)

**Comment by PhpFoxJohnJr** [comment]
Yes, I will get one...I just shut off the #966 fix but now I have no share link or report link.  The person who reported the missing claim button must not have seen fix #966.  Really that new claim button is to loud and too big for a one time click (maybe or ever).  They should have just implemented #966 as default.

**Comment by PhpFoxJohnJr** [comment]
![page-issues](https://cloud.githubusercontent.com/assets/14913734/13153455/db546640-d639-11e5-8cb0-5ca2347b8886.png)

**Comment by PhpFoxJohnJr** [comment]
With the new bootstrap theme looks like now the green claim button on the bottom left has now grey text so it is hard to see.  I don't even see the report button but I see the share button.  I can't remember now...I think there was report button but I can't check since I have upgrade everything...sorry.

**Comment by PhpFoxJohnJr** [comment]
I can see having the Join button or like button on the image because out of 100 members...99 will pick to join or like but only 1 person will claim a page and that only if they didn't make it.  We should still have a claim link under the share link but to have those two big green things seems like a waste of space for the 0 - 1% of the members to actually click.

**Comment by Data66PF** [comment]
The claim text button issue is fixed for the default block we have. It was a bug because it was with the default one and not one being remade via that tutorial if you get what I mean.

You could change this feature request to be to add a Report button for pages as they don't have one.
