### ISSUE TITLE
Settings --> security page need option to disable active save

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#52]
In the Settings --> security page, there needs to be an option to disable active the active save feature so you have to manually save it instead.

The reason for this is if you unintentionally put the wrong thing in an input area and then click on a different area or if a cat jumps on the keyboard or mouse you could potentially be in a world of hurt as it will auto save the settings.

**Comment by Data66PF** [comment]
This feature request is not complete. Please provide more details or screenshots or video example.

**Comment by lueung** [comment]
http://prntscr.com/ah6kne

**Comment by Data66PF** [comment]
Next time can you please put the screenshot in the github itself instead of a link?
