### ISSUE TITLE
Sort Rating on Developers Profile doesn’t apply correctly

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox-feature-requests#56]
While browsing developers on store.phpfox.com (https://store.phpfox.com/techie/browse), users can sort for developers by “Highest Rated” criteria. However, the result seems displaying incorrectly.
 
Currently, the result is displaying by showing the highest ‘average rating point’ to the lowest. It seems not to be a fair displaying way.  As an example, developer A currently has 11 ‘5 stars’ and 1 ‘4 stars’. Developer B has only 1 ‘5 star’. So based on those ratings, developer A should be obviously rated higher than developer B. However, the current system metric of phpfox.com displays B higher than A when sorting by “Highest Rated”.

From our opinion, to be fair, when sorting “Highest Rated”, the ranks of developers should be sorted by the number of ‘5 stars’ that the developers have earned first. In the event of a tie in the number of ‘5 stars’, the number of ‘4 stars’ is taken into consideration, and then following by the number of ‘3 stars’ , ‘2 stars’, ‘1 star’.

**Comment by Data66PF** [comment]
As this request area was intended only for core feature requests, please send us a ticket with details for the things you suggest for our store. You can reach us in the new client area, https://clients.phpfox.com/ . We do appreciate improvement ideas and did have a lot on our list to improve too.
