### ISSUE TITLE
Polls and Quizzes cant be restricted to group

### ISSUE THREAD

**Issue by mans71** [moxi9/phpfox-feature-requests#57]
One of the strangest things i phpfox in my opinion is that polls and quizzes are created globally or just for friends and/or selected users.

I think it makes more sense to use the poll and quizzes in a group, in other words, let the group be the security object.

What I mean is that when I create a poll I want to use it in my group, and only users that are in this group (have liked or joined the group) should be the ones to see and use the poll.

So I propose that the drop-down under privacy when I create the poll has a new option called "Members of the group XX" where I can select the group to be the security group.

Another way to go would be to move the quiz and polls to beneath the groups, just as events, photos etc are located.

I can see almost no case where one would want to create a poll without any context (group) - it seems misplaced at the moment.

**Comment by flarecoins** [comment]
here page /group section not showing quiz & poll .......

**Comment by flarecoins** [comment]
on phpfox 4.7.5 v.

**Comment by flarecoins** [comment]
third party need payment if they created this support option ... phpfox team .. need to provide this option ... because your promise .. you give all features with script ... & here you invite other people to make this .. if they want money ... its bad to phpfox owners .. not happy
