### ISSUE TITLE
[4.2.1] Repositioned Covers Issue

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox-feature-requests#60]
_From @Spaninet on February 10, 2016 16:15_

Only a very small portion of the repositioned covers appear on mobile devices.

_Copied from original issue: moxi9/phpfox#1108_

**Comment by Data66PF** [comment]
can't reproduce in iPhone 5c using standard sized cover photo image.
phone:
![img_0161](https://cloud.githubusercontent.com/assets/6908282/12975105/14f2c120-d087-11e5-8302-aaa3a8adb572.PNG)
desktop:
![pagecover](https://cloud.githubusercontent.com/assets/6908282/12975109/22a2943a-d087-11e5-8684-dacd80989945.png)

**Comment by Data66PF** [comment]
_From @optiroot on February 20, 2016 18:40_

I can confirm this.

Sometimes it shows all the photo with black below it (you can see the block near "Unlike") and sometimes it just shows the 50% of the cover. The rest is pushed up.

**Comment by Data66PF** [comment]
_From @neil96 on February 22, 2016 1:59_

I saw the problem.

**Comment by Data66PF** [comment]
_From @Spaninet on February 23, 2016 19:12_

A screenshot:

![Screenshot](https://community.phpfox.com/file/attachment/2016/02/bc7cc0d02ebb489c2dbf485f5353931c.png)

**Comment by neil96** [comment]
Implemented in 4.3.0
