### ISSUE TITLE
Include / embed video in forum

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox-feature-requests#63]
Currently you cannot include or embed video in a forum. In previous version of phpfox you can include video in blogs and forums. It would be nice to be able to include videos in forums.

**Comment by Data66PF** [comment]
As we disabled html for safety, this would re-introduce a security risk. Will have to see how this could be done safely, if possible. Since youtube uses iframes, and that is not safe, it would need a different way to embed, perhaps with bbcode.

**Comment by Ylmzef** [comment]
:+1:

**Comment by Data66PF** [comment]
Please get a third party to do this. They will need to be up to date on security for this feature.
