### ISSUE TITLE
Option to Import/Export Countries and Stetes/Provinces

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox-feature-requests#65]
In Site.com/admincp/core/country/ we need bulk import (and export) options, instead of adding States/Provinces manually one by one. This should function like Language Packs.

**Comment by Data66PF** [comment]
More details please. Thanks.

**Comment by Data66PF** [comment]
More details needed for how you prefer this to function. We did have a basic option before. Do you just want that back or do you have some idea of how this would work best?

**Comment by Spaninet** [comment]
Where is the basic option? I haven't seen any option before opening this feature request.

**Comment by Data66PF** [comment]
In v3.

**Comment by Spaninet** [comment]
The option in v3 is basic.

The tool I am requesting wish to have:

- An Export option to create a ZIP file (like a language pack) of a single country or all countries with their states/provinces.
- Import option, to load all the content of the pack into another site.
- Country Packs of a single country/all countries can be published and downloaded from the store.
- Language packs can include translations to different languages.

**Comment by Data66PF** [comment]
A third party developer could actually make this feature based on the v3 setting to enable that and add it as an app at the store though. As you are developing things, you might want to install a v3 site and go look at the old setting. Make a plugin app with the hook to enable that or make a better version of what we had.

**Comment by Data66PF** [comment]
Import/Export is part of the v4.4 product

**Comment by Spaninet** [comment]
Cool
