### ISSUE TITLE
Add more fields on app’s posting

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox-feature-requests#68]
While viewing an app’s posting on store.phpfox.com, it would be more helpful for buyers if there were 2 more fields: “Dependency” and “Change Log”. So if possible, please add those 2 fields so developers can add those information while publishing the apps.

**Comment by Data66PF** [comment]
As this request area was intended only for core feature requests, we will discuss internally whether to have these suggestions here or in a private ticket to us. 

Do you have a screen shot of what you want?

Do you mean Dependency to be the version or something else?

Changelog is best in some other area than making a long view in the app in admincp. Perhaps we can discuss this internally to figure something out.

**Comment by Data66PF** [comment]
As this request area was intended only for core feature requests, please send us a ticket with details for the things you suggest for our store. You can reach us in the new client area, https://clients.phpfox.com/ . We do appreciate improvement ideas and did have a lot on our list to improve too.
