### ISSUE TITLE
404 handling

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#75]
Currently it just displays a file not found. It would be nice to have more 404 handling options from admincp like a redirect to address or search whatever keywords it was from or just a custom message.

**Comment by Data66PF** [comment]
I use http://scripttechs.com/article/193/site-marketing/#180 custom google search for my 404. Easy to do in phrase manager.

**Comment by lueung** [comment]
Nice. Any way to keep the search results on site?

**Comment by Data66PF** [comment]
You set that in the google settings. I suggest to look at google for their search tool and see what options you have for keeping the results on site.
