### ISSUE TITLE
Prevent someone you block from liking your posts.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox-feature-requests#76]
When a user block someone, chances are they want nothing to do with them period. When a blocked user goes to like a post, the system should do a quick check to see of the user of that post has imposed a block against the user.  If yes, the liker gets a message such as

You are not allowed to like this users posts, or
Sorry, this user has disallowed your liking this post

This would not be limited to new posts originated by the user but the user imposing the block, but replies, comment posts across all services too.

**Comment by Data66PF** [comment]
Webwolf has a plugin for this at my ScriptTechs just so you know. :) It's free. Just contact him to see if he'll release it as he already has a Karma block feature (free) that allows full user blocking for comments, etc and added the Like and a few other things for another client, free. http://scripttechs.com/marketplace/162/karma-user-blocks/

It is for v3 but he said it works in v4 I believe.

As for this feature request, I need to see with our lead developer how much overhead this would add to queries for the site.

**Comment by Gatsby-PF** [comment]
It sounds like a nice module.  My only concern is, being v3 technology that just happens to work in v4, what kind of security holes might it make available?  As for the queries, the system would have to query the user/post commented to, as well as the user liking/commenting to the post so I would make a rough guess that an additional query to determine the likers block status vis-a-vis the blocker would be needed before dropping the hatchet.

**Comment by Data66PF** [comment]
The issue I see is with active sites. I've a client in my ScriptTechs who has a very large and active phpFox community. 10k users with 300 online concurrently. The feed has massive amounts of content added every second. If you blink, for example, you will miss at least 3 full feed loads (meaning you have to scroll down a minimum of 3 times just to see the content that's been added during that brief time). Her photo section is 150 gig just for that one area. These are all real users. Now, imagine a site like that with all of that activity. 300 users x their friends x comments/likes/feeds/photos/etc etc etc. 

Concerned with how this could impact something like that and how a database can handle all of that and not create a bottleneck or other issues. 

Now, imagine the other huge site that I know of with over 1 million users and approx 6000 online concurrently (phpFox v3 site). How will this impact if he upgrades and we have this app for blocking?

**Comment by Gatsby-PF** [comment]
It shouldn't be too difficult to prove out on a smaller scale.  Any additional server usage difference on a system of 10 users with this feature versus without out it should scale forward proportionally for any larger quantity.

**Comment by Data66PF** [comment]
I do think we need an option for total blocking as a few other scripts have. I think we need to consider the impact on active sites and possibly an admin warning that it can cause heavy database queries and could require multiple server environment, etc. Will mark it Interest so we can at least look and see how big an app this would be. If not too big and involved, perhaps we can include it once we are doing features.

I think this would just need to be a total block as opposed to just Likes. Need feedback. Example: user a blocks user b. Right now, that only blocks user b from contacting user a. In a total block, user a sees no content from user b and cannot have any interactions from user b at all.

**Comment by darkname** [comment]
At least it would be great if for example A blocks B, then B automatically also block A. I do not think it requires a lot of changes. Because in PHPFox v4 right now on the home page (where the feeds are), if B posts something, then A blocks B, A is able to comment on B's post and B cannot even block A. I am aware about the setting: make the network friends only, but that's not a solution. Thanks.
