### ISSUE TITLE
SEO Improvements

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#78]
Dear Team, 

We now have SEO settings in Admin cp, which is fantastic but would Iike to request some improvements to it. 

1) ALT attribute in Image tags should be auto populated with either image name or caption or description of photos being uploaded. 
2) Settings->SEO should also include settings for videos just like in V3
3) Does events and forums meta description gets picked up automatically when a event is created or forum post is made? 
4) Can we have a placeholder for adding keywords/tags and description while drafting a blog itself? Because each blog will be unique and these generic keywords may not be of much help for SEO.

**Comment by srikumar101** [comment]
Adding on to the list.. 
5) <H1> and <H2> tags are missing.. this can be added to blogs, events and forums.. all titles cab be in H1 tags and sub headers in H2 tags. Especially if blogs can be given default SEO features like wordpress it will see a great improvement in ranking for the content added.. 
6) Add rel="Publisher" tag whic is for linking site to Google+ Page which will improve ranking.

**Comment by Data66PF** [comment]
Rejected due to not following the instructions of ONE request per issue posted. We are already looking at improvements though.
