### ISSUE TITLE
Enable upgrade via admincp

### ISSUE THREAD

**Issue by vanucci** [moxi9/phpfox-feature-requests#80]
Give the webmaster the ability to upgrade from the acp rather than download the file, upload  and then run the upgrade script. 

Scenario

Current Version 
4.3

Upgrade Available
4.3.1 Upgrade now  <--- click

This option would do the process automatically

**Comment by Data66PF** [comment]
This is something we discussed in v2 and v3 as well. The problem with automated upgrades is server, customizations, apps/add ons, etc. This could be a nightmare. We are discussing this internally again but most likely, we won't do this due to the headaches it will create.
