### ISSUE TITLE
Searching feature for apps

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox-feature-requests#84]
Current apps don't have core searching feature. So it would be better to add it into all of the apps, including: text field for searching, and other filters (such as: Most Viewed, Most Liked, Show: 5 per page, When: All Time, etc...) which are supported in the correspondent apps.

**Comment by Data66PF** [comment]
As this request area was intended only for core feature requests, please send us a ticket with details for the things you suggest for our store. You can reach us in the new client area, https://clients.phpfox.com/ . We do appreciate improvement ideas and did have a lot on our list to improve too.

**Comment by Nghiep-YouNet** [comment]
That was the suggestion intending for the core feature of phpFox. However we've checked the latest version 4.3.0 and this feature has been already included. So it's good for now. Thank you very much for your concerns and supports.
