### ISSUE TITLE
Pagination for apps

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox-feature-requests#85]
On both core Front End and Back End, it is currently using "auto load" feature to load for more items. It would be better to add another "pagination" feature so users can have more flexibility to browse for items.

**Comment by Data66PF** [comment]
Do you mean in AdminCP? If so, we can look at this in this feature request area. If you mean for the store, we would need you to include this in your ticket please.

**Comment by Nghiep-YouNet** [comment]
Sorry for the confusion. Yes, we mean AdminCP and also on Front End. However we've checked the latest version 4.3.0 and this 'pagination' feature has been already included. So thank you very much for your concerns and supports.
