### ISSUE TITLE
Recommended users settings to disable in admincp

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox-feature-requests#87]
Recommended users settings to disable in admincp

**Comment by Ylmzef** [comment]
:+1:

**Comment by Data66PF** [comment]
Please next time have a fuller description as our instructions show, to avoid rejection.

This appears to be a suggestion to add a setting to disable the Recommended Users "block", for lack of a better word, from appearing in the Member browse page.

**Comment by lueung** [comment]
I believe Niel mentioned he fixed.

**Comment by neil96** [comment]
I fixed in on moxi9/phpfox#1203

**Comment by Data66PF** [comment]
This is a duplicate then.
