### ISSUE TITLE
Default Join button for pages

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox-feature-requests#88]
Dear Team, 

Can you please make Join button visible by default on pages? As I see it in google analytics, many visitors visit the website.com/pages or website.com/page-name and leave the site as they can't find join button. We can increase conversion rate by highlighting join button. When they click on it, if they are not logged in already then login/register pop-up should show up. 
This will be very useful for overall product.

**Comment by Data66PF** [comment]
This is something you'll need to do by a customization as we had too many clients that wanted it removed for guests.
