### ISSUE TITLE
Separate Pages blog permission for "Who can view blogs : Anyone" with additional permission of "who can create blog"

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox-feature-requests#89]
The way that the pages blog currently work is that if you let any "Anyone" view the blog, it also lets anyone write on that groups blog without being part of the pages group. This has the potential disaster of a drive by blogging of every pages blog.

The view by anyone setting should let anyone view, but it should not let them blog on the pages unless they become part of the group. This way the entire site or public can still benefit from the blog, but can't vandalize or spam it.

The "who can create blog" will give a finer grain of control.

**Comment by Data66PF** [comment]
I'll leave this open for now but I found your bug report and marked it a bug as this is not working properly.

**Comment by Data66PF** [comment]
this was solved in the issue tracker as a bug.
