### ISSUE TITLE
Temporary admin login without IP restriction

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#90]
On rare occasion I might have to give someone admin access to the site... the issue is they will not be able to login to the admincp because their IP is not on the security list. So I have to either delete everyone's current admin IP's or add the IP of the temporary admin's ip so that he/she can login to the admincp.

It would be nice to enable  create a temporary admin account that is not tied into to the security IP for them to access admincp for a short period of time in order to fix stuff.

**Comment by Data66PF** [comment]
So you want a setting to basically grant admincp access for a set amount of time?

**Comment by lueung** [comment]
Yes. exactly
