### ISSUE TITLE
Please add analytics to website admin and page admin

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#92]
Please add analytics to website admin and page admin.  We know there are 3 party analytics but there nothing like your own. And fir page admin they have to know how many engaments, impression's etc....  They got could make them post more and do more. 
Also internal analytics is the best way page admin know that they followers are with them.

**Comment by Data66PF** [comment]
This is a bigger request that is better done by a third party developer.

**Comment by GreenMan123** [comment]
Please give it a try or integate with open source analytics software.
