### ISSUE TITLE
Please add some thing for developers to add to there website/other website/

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox-feature-requests#93]
Well there are going to be website developer's which would like to add chat, comment and share or like buttons to there site from phpfox site what are you doing about this. Please make phpfox site users interact everywhere do everwhere/Chat, like, comment and share or signup to a website using phpfox/. Please add this nice feature.

**Comment by Data66PF** [comment]
Developers must purchase a license for our script. They can enable chats and things if they want with their purchased license.

**Comment by GreenMan123** [comment]
What i mean is an api

**Comment by Data66PF** [comment]
There is an api. There are documents in our tutorials for using it if that is what you want. https://docs.phpfox.com/display/FOX4DEVDOC/phpFox+4+Developer+Document
