### ISSUE TITLE
Tooltip to show app's name when hovering

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox-feature-requests#94]
In AdminCP >>> Apps, under each app icon, there is an app name. However, in some cases the app name is quite long so it cannot appear fully. So it would be really helpful if we can add a tooltip that displays full app name when user hovers each app icon. Thank you.

**Comment by Data66PF** [comment]
For mobile devices would that work well? Should we see about making a max length of the name perhaps? Maybe each app should show the developer's name by default and then the developers won't need to add their name before the app name. What do you think of something like that?
