### ISSUE TITLE
oEmbed support in feed

### ISSUE THREAD

**Issue by talkbacker** [moxi9/phpfox-feature-requests#95]
The small popup window for YouTube is pretty awkward/outdated. [oEmbed support](http://oembed.com/) in the feed for YouTube, Vimeo, Soundcloud, etc. would a useful core feature.

**Comment by Data66PF** [comment]
This is incomplete for us to know what you want. Please be more detailed as we already have oEmbed support. We need more information.

**Comment by talkbacker** [comment]
In-line oEmbeds is the operative phrase I didn't include. YouTube videos opening up in a popup overlay instead of playable within the feed is less than elegant.
