### ISSUE TITLE
Item-based Feed Control

### ISSUE THREAD

**Issue by talkbacker** [moxi9/phpfox-feature-requests#96]
Giving admin control of which types of posts/content show up in the feed. There are some crude plugins that can do this, but it would be a useful core feature to reduce "content noise" on larger social networks. Networks that focus more on photos, video, and status content may not necessarily benefit from relationship status and friendship posts in the feed. The ability to to switch items on and off in the admin feed settings would make phpfox hugely customizable in terms of what type of content is the focus. Here's a mock-up screenshot of what those Admin controls could look like.

![item_base_feed_control](https://cloud.githubusercontent.com/assets/18018835/13973171/ffd700f6-f06d-11e5-82a6-19c2bd4f665a.gif)

This could be extended even further by having a third option for "Friends only" for each item. If the feed were in public mode, certain items could be turned on for just friends. For instance, on a large network an Admin might want to show Relationship status changes to friends but not everyone. This would reduce noise, but give relevant feed updates about friends.

**Comment by Data66PF** [comment]
This feature system is for smaller feature requests. This request requires extensive work and there is already a third party product for Advanced Wall functions from YouNet that they could be bringing to V4 if you check with them. We cannot do this feature as part of our small improvements. Please check with third party vendors or please post at the community as we will also look there later on when we do bigger features for the script.

**Comment by talkbacker** [comment]
YouNet doesn't provide any of the admin functionality laid out in this feature proposal.That's a front end feature. I appreciate the suggestion though. What's the proper channel for suggesting larger improvements to phpFox's core, or is the phpFox not interested in such improvements?

**Comment by Data66PF** [comment]
We are leaving a lot of room for third party developers to make apps and improve what they already offer. Since YouNet already has an advanced wall, they would be a good one to ask.

However, you can request bigger feature requests at our https://community.phpfox.com in the feature request area after first searching there to see if it is already a request.
