### ISSUE TITLE
Collect users phone numbers

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox-feature-requests#98]
Collect users phone numbers under profile from veritification step.
Because users can signup again with same phone number.

**Comment by Data66PF** [comment]
Is this to collect phone numbers or to verify by phone number to ensure the same phone number is not used? I assume this is for the two step authentication settings which will be made into apps in the near future.

**Comment by Ylmzef** [comment]
Yes as e-mail verify.
Collect phone numbers under profile and let users set privacy settings for this field who can see phone number.

**Comment by Data66PF** [comment]
One feature request per request. We can not look at the option to set privacy for this request.

This request is only to look at adding a "phone number" check so that a site admin can choose to set it so that duplicate phone numbers are not allowed.

**Comment by GreenMan123** [comment]
As a choice phone Numbers should also be alternatives for email address. So let use phone numbers used for varification and used as a means of contacting people for notifications and security varifications and so on.......

**Comment by GreenMan123** [comment]
In my country most people have phone numbers but only a few people have an email address and very little of use our emails to connect and communicate with peoples.
